// import { Inter } from "next/font/google";
import { Indie_Flower } from "next/font/google";
import { cn } from "@/lib/utils";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const myFont = Indie_Flower({
  subsets: ["latin"],
  weight: "400", 
});


export const metadata = {
  title: "Video Downloader",
  description: "Insta/YouTube video Downloader",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased mx-auto max-w-[1440px]",
          myFont.className
        )}
      >

        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
